import pickle
import numpy as np
import streamlit as st
import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors



# Loading the Saved Model
loaded_model = pickle.load(open('trained_model.sav', 'rb'))


def dementia_prediction(input_data):

    input_data_as_numpy = np.asarray(input_data)
    input_data_reshape = input_data_as_numpy.reshape(1, -1)

    prediction = loaded_model.predict(input_data_reshape)

    if prediction[0] == '0':
        return "The patient is NonDemented"
    elif prediction[0] == '1':
        return "The patient is Demented"
    else:
        return "The patient is Converted"


# -------- PDF Generator --------
def generate_pdf_report(name, inputs, diagnosis):

    filename = "Dementia_Report.pdf"

    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(filename, pagesize=A4,
                            rightMargin=40, leftMargin=40,
                            topMargin=40, bottomMargin=40)

    content = []

    # -------- Title --------
    content.append(Paragraph("<para align=center><b>Dementia Prediction Medical Report</b></para>", styles["Title"]))
    content.append(Spacer(1, 10))

    # -------- Patient Info --------
    content.append(Paragraph(f"<b>Patient Name:</b> {name}", styles["Normal"]))
    content.append(Paragraph(f"<b>Date:</b> {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["Normal"]))
    content.append(Spacer(1, 10))

    # -------- Table Data --------
    labels = [
        "Visit", "MR Delay", "Gender", "Hand", "Age", "Education",
        "SES", "MMSE", "CDR", "eTIV", "nWBV", "ASF"
    ]

    table_data = [["Parameter", "Value"]]

    for l, v in zip(labels, inputs):
        table_data.append([l, str(v)])

    table = Table(table_data, colWidths=[200, 200])

    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))

    content.append(table)
    content.append(Spacer(1, 15))

    # -------- Result Section --------
    content.append(Paragraph(f"<b>Prediction Result:</b> {diagnosis}", styles["Heading2"]))
    content.append(Spacer(1, 10))

    # -------- Footer --------
    content.append(Spacer(1, 20))
    content.append(Paragraph("<para align=center>This report is generated by the FC Prediction System.</para>", styles["Normal"]))

    doc.build(content)

    return filename



def main():

    st.title('Dementia Prediction Web App')

    # Patient Name
    Name = st.text_input('Enter the Patient Name')

    # Row 1
    r1c1, r1c2, r1c3, r1c4 = st.columns(4)
    with r1c1:
        Visit = st.number_input('Visit', min_value=0, step=1)
    with r1c2:
        MR_Delay = st.number_input('MR Delay', min_value=0, step=1)
    with r1c3:
        Gender = st.selectbox("Gender", ["Select", "Male", "Female"])
    with r1c4:
        Hand = st.selectbox("Hand", ["Select", "Right", "Left"])

    # Row 2
    r2c1, r2c2, r2c3, r2c4 = st.columns(4)
    with r2c1:
        Age = st.number_input('Age', min_value=0, step=1)
    with r2c2:
        EDUC = st.number_input('Education (Years)', min_value=0, step=1)
    with r2c3:
        SES = st.number_input('Socioeconomic Status')
    with r2c4:
        MMSE = st.number_input('MMSE Score')

    # Row 3
    r3c1, r3c2, r3c3, r3c4 = st.columns(4)
    with r3c1:
        CDR = st.number_input('CDR')
    with r3c2:
        eTIV = st.number_input('eTIV', min_value=0, step=1)
    with r3c3:
        nWBV = st.number_input('nWBV', format="%.3f")
    with r3c4:
        ASF = st.number_input('ASF', format="%.3f")

    diagnosis = ''

    button_col1, button_col2, button_col3, button_col4, button_col5 = st.columns(5)
    with button_col3:
        if st.button("Test Result"):

            if Name.strip() == "":
                st.error("Please enter Patient Name.")
                return

            if Gender == "Select" or Hand == "Select":
                st.error("Please select Gender and Hand.")
                return

            Gender_val = 0 if Gender == "Male" else 1
            Hand_val = 0 if Hand == "Right" else 1

            try:
                input_values = [
                    float(Visit), float(MR_Delay), Gender_val, Hand_val,
                    float(Age), float(EDUC), float(SES), float(MMSE),
                    float(CDR), float(eTIV), float(nWBV), float(ASF)
                ]
            except ValueError:
                st.error("Please enter valid numeric values.")
                return

            diagnosis = dementia_prediction(input_values)

            # Generate PDF
            pdf_file = generate_pdf_report(Name, input_values, diagnosis)

            with open(pdf_file, "rb") as f:
                st.download_button(
                    label="Download PDF Report",
                    data=f,
                    file_name="Dementia_Report.pdf",
                    mime="application/pdf"
                )

    # Show diagnosis in center
    if diagnosis == 'The patient is NonDemented':
        st.markdown("<h3 style='text-align: center; color: green;'>The patient is NonDemented</h3>", unsafe_allow_html=True)
    elif diagnosis == 'The patient is Demented':
        st.markdown("<h3 style='text-align: center; color: red;'>The patient is Demented</h3>", unsafe_allow_html=True)
    elif diagnosis == 'The patient is Converted':
        st.markdown("<h3 style='text-align: center; color: orange;'>The patient is Converted</h3>", unsafe_allow_html=True)


if __name__ == '__main__':
    main()
